# Name(s)
**PUT YOUR FULL NAME(S) HERE**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

- Other than downloading the assignment zip on github and uploading to jupyterlabs ide ourselves. how can we import github classroom projects easily into jupyterlab. 
- How does the md file sync with the .iypynb automatically?
- Due to how the .md file and .ipynb file sync. Should we only edit in the .md file then turn in the .ipynb file?

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [7]:
import numpy as np

a = np.full((4,6), 2)
print(a) 

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


## Exercise 2

In [12]:
# kinda confused on what a leading diagonal is...
b = (2 * np.eye(4,6)) + np.ones((4,6))
print(b)

[[3. 1. 1. 1. 1. 1.]
 [1. 3. 1. 1. 1. 1.]
 [1. 1. 3. 1. 1. 1.]
 [1. 1. 1. 3. 1. 1.]]


## Exercise 3

In [13]:
c = a * b
print(c)

# because the dot product needs a x b , b x c matrix layout for operands

[[6. 2. 2. 2. 2. 2.]
 [2. 6. 2. 2. 2. 2.]
 [2. 2. 6. 2. 2. 2.]
 [2. 2. 2. 6. 2. 2.]]


## Exercise 4

In [19]:
d = np.dot(a.transpose(), b)
e = np.dot(a,b.transpose())
print(d)
print(d)

[[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]
[[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]


## Exercise 5

In [21]:
def runIt():
    print("Hello World. This environment is my new habitat...")
    
runIt()

Hello World. This environment is my new habitat...


## Exercise 6

In [30]:
def details():
    r = np.random.random((4,6))
    print("sum: ", r.sum())
    print("mean: ", r.mean())

details()
    

sum:  14.612604264185627
mean:  0.6088585110077345


## Exercise 7

In [37]:
def loopy(arr):
    ones = 0
    for row in arr:
        for i in row:
            if i == 1:
                ones += 1
    return ones
                
o = np.eye(4,6)
print(o)
print("ones count: ", loopy(o))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
ones count:  4


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [42]:
import pandas as pd

ad = pd.DataFrame(a, index=list(range(4)), columns=list(range(6)))
print(ad)

   0  1  2  3  4  5
0  2  2  2  2  2  2
1  2  2  2  2  2  2
2  2  2  2  2  2  2
3  2  2  2  2  2  2


## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [43]:
bd = pd.DataFrame(b, index=list(range(4)), columns=list(range(6)))
print(bd)

     0    1    2    3    4    5
0  3.0  1.0  1.0  1.0  1.0  1.0
1  1.0  3.0  1.0  1.0  1.0  1.0
2  1.0  1.0  3.0  1.0  1.0  1.0
3  1.0  1.0  1.0  3.0  1.0  1.0


## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [44]:
cd = pd.DataFrame(c, index=list(range(4)), columns=list(range(6)))
print(cd)

     0    1    2    3    4    5
0  6.0  2.0  2.0  2.0  2.0  2.0
1  2.0  6.0  2.0  2.0  2.0  2.0
2  2.0  2.0  6.0  2.0  2.0  2.0
3  2.0  2.0  2.0  6.0  2.0  2.0


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [61]:
def data_ones(arr):
    ones = 0
    for i in range(len(arr)):
        for j in range(len(arr.iloc[i])):
            if 1 == arr.iloc[i,j]:
                ones += 1
    return ones

nd = pd.DataFrame(np.eye(4,6), index=list(range(4)), columns=list(range(6)))
print(nd)

print("# of ones: ",data_ones(nd))
    

     0    1    2    3    4    5
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0
# of ones:  4


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [70]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [78]:
cols = titanic_df['name']
cols


sex
female                      Allen, Miss. Elisabeth Walton
male                       Allison, Master. Hudson Trevor
female                       Allison, Miss. Helen Loraine
male                 Allison, Mr. Hudson Joshua Creighton
female    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                               ...                       
female                               Zabour, Miss. Hileni
female                              Zabour, Miss. Thamine
male                            Zakarian, Mr. Mapriededer
male                                  Zakarian, Mr. Ortin
male                                   Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [77]:
titanic_df.set_index('sex',inplace=True)


KeyError: "None of ['sex'] are in the columns"

## Exercise 14
How do you reset the index?

In [80]:
titanic_df.reindex(index=titanic_df[0], columns=list(titanic_df.columns))

KeyError: 0